# Generated by Django 5.2.17 on 2026-09-24 17:10

import api.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_title', models.CharField(default='New Diagnostic Session', max_length=255)),
                ('car_make', models.CharField(blank=True, max_length=100, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('car_mileage', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('diagnosed', 'Diagnosed'), ('booked', 'Booked'), ('closed', 'Closed')], default='active', max_length=20)),
                ('troubleshooting_stage', models.CharField(default='initial_inquiry', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('system', 'System')], max_length=10)),
                ('text', models.TextField()),
                ('is_ai_generated', models.BooleanField(default=True)),
                ('triage_tag', models.CharField(default='chat', max_length=50)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('media_type', models.CharField(blank=True, max_length=20, null=True)),
                ('suggested_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_title', models.CharField(max_length=255)),
                ('primary_cause', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low - Minor issue'), ('medium', 'Medium - Attention needed'), ('high', 'High - Urgent repair'), ('critical', 'Critical - Do not drive')], default='medium', max_length=20)),
                ('urgency_level', models.CharField(choices=[('immediate', 'Immediate (Within 24-48 hrs)'), ('soon', 'Soon (Within 1-2 weeks)'), ('routine', 'Routine Maintenance'), ('monitor', 'Monitor closely')], default='soon', max_length=20)),
                ('is_driveable', models.BooleanField(default=True)),
                ('symptoms', models.JSONField(blank=True, default=list)),
                ('suggested_repairs', models.JSONField(blank=True, default=list)),
                ('estimated_cost_range', models.CharField(default='$150 - $350', max_length=100)),
                ('estimated_labor_hours', models.CharField(default='1.5 - 2.5 hrs', max_length=50)),
                ('safety_warning', models.TextField(blank=True, default='')),
                ('diy_feasibility', models.CharField(default='Professional Recommended', max_length=50)),
                ('recommended_service_name', models.CharField(default='Standard Inspection & Repair', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='api.conversationsession')),
            ],
        ),
        migrations.CreateModel(
            name='MechanicBooking',
            fields=[
                ('id', models.CharField(default=api.models.generate_booking_code, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('customer_email', models.EmailField(max_length=254)),
                ('car_make', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_year', models.IntegerField()),
                ('car_mileage', models.CharField(blank=True, default='', max_length=50)),
                ('service_requested', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('shop_visit', 'Certified Workshop Visit'), ('mobile_mechanic', 'Doorstep Mobile Mechanic'), ('emergency_towing', 'Emergency Towing & Diagnostics')], default='shop_visit', max_length=30)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(max_length=50)),
                ('customer_address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('estimated_cost', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.diagnosisreport')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.conversationsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('other', 'Other')], default='image', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('ai_analysis', models.TextField(blank=True, default='')),
                ('detected_indicators', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.conversationsession')),
            ],
        ),
    ]
